upstreamProjects:
  Mule-runtime/api-annotations/master
mavenSettingsXmlId: mule-runtime-maven-settings-MuleSettings
projectType: runtime
jdkTool: OPEN-JDK17
mavenTool: "3.9.9"
additionalTestConfigs:
  jdk21:
    testJdkTool: TEMURIN-JDK21
