upstreamProjects:
  Mule-runtime/api-annotations/master-OCTOBER-2024
mavenSettingsXmlId: mule-runtime-maven-settings-MuleSettings
projectType: runtime
jdkTool: OPEN-JDK17
additionalTestConfigs:
  jdk21:
    testJdkTool: TEMURIN-JDK21
